###
### BrandController Requests
###
localhost

### GET all brands
GET http://localhost:8080/api/brands
Accept: application/json

### GET brand by name
GET http://localhost:8080/api/brands/Pepsi
Accept: application/json

### POST (create) a new brand

POST http://localhost:8080/api/brands
Content-Type: application/json
Accept: application/json

{
  "name": "New Brand",
  "country": "New Country"
}

### PUT (update) a brand by name
PUT http://localhost:8080/api/brands/Fanta
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Brand",
  "country": "Updated Country"
}

### DELETE a brand by name
DELETE http://localhost:8080/api/brands/Pepsi

###
### DrinkController Requests
###
localhost

### GET a drink by name
GET http://localhost:8080/api/drinks/Fanta_orange
Accept: application/json

### GET all drinks
GET http://localhost:8080/api/drinks
Accept: application/json

### POST (create) a new drink
POST http://localhost:8080/api/drinks
Content-Type: application/json
Accept: application/json

{
  "name": "New Drink",
  "price": 10,
  "year": "2023",
  "brandId": "592a37d8-67bc-4f9d-949d-e7a606e0f01c"
}

### PUT (update) a drink by name
PUT http://localhost:8080/api/drinks/Fanta_orange
Content-Type: application/json
Accept: application/json

{
  "name": "Fonta",
  "price": 12,
  "year": "2021"
}

### DELETE a drink by name
DELETE http://localhost:8080/api/drinks/Fanta
