### GET all drinks
GET http://localhost:8081/api/drinks
Accept: application/json

### GET a drink by name
GET http://localhost:8081/api/drinks/name/Fanta_orange
Accept: application/json

### GET a drink by name, non-existing
GET http://localhost:8081/api/drinks/name/Fanta_grape
Accept: application/json

### POST (create) a new drink
POST http://localhost:8081/api/drinks
Content-Type: application/json
Accept: application/json

{
  "name": "New Drink",
  "price": 10,
  "year": "2023",
  "brandId": "592a37d8-67bc-4f9d-949d-e7a606e0f01c"
}

### PUT (update) a drink by name
PUT http://localhost:8081/api/drinks/name/Fanta_orange
Content-Type: application/json
Accept: application/json

{
  "name": "Fonta",
  "price": 12,
  "year": "2021"
}

### DELETE a drink by name
DELETE http://localhost:8081/api/drinks/name/Fanta
